CREATE DATABASE IF NOT EXISTS lost_found_ai CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lost_found_ai;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20) NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NULL,
  role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  post_type ENUM('LOST','FOUND') NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  color VARCHAR(50) NULL,
  brand VARCHAR(100) NULL,
  location VARCHAR(255) NOT NULL,
  event_date DATETIME NOT NULL,
  contact VARCHAR(100) NULL,
  reward DECIMAL(10,2) NOT NULL DEFAULT 0,
  status ENUM('OPEN','MATCHED','CLOSED') NOT NULL DEFAULT 'OPEN',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_posts_user FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT fk_posts_category FOREIGN KEY(category_id) REFERENCES categories(id),
  INDEX idx_posts_type_category(post_type, category_id),
  FULLTEXT INDEX ftx_posts_text(title, description, location)
);

CREATE TABLE IF NOT EXISTS images (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT UNSIGNED NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_images_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_features (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  image_id BIGINT UNSIGNED NOT NULL,
  embedding_path VARCHAR(255) NULL,
  model_name VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_image FOREIGN KEY(image_id) REFERENCES images(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS matches (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lost_post_id BIGINT UNSIGNED NOT NULL,
  found_post_id BIGINT UNSIGNED NOT NULL,
  similarity_score FLOAT NOT NULL,
  ai_model VARCHAR(100) NOT NULL,
  status ENUM('PENDING','CONFIRMED','REJECTED') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_match_lost FOREIGN KEY(lost_post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_match_found FOREIGN KEY(found_post_id) REFERENCES posts(id) ON DELETE CASCADE,
  UNIQUE KEY uk_match_pair(lost_post_id, found_post_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notifications_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_notifications_user_read(user_id, is_read)
);
